server:
  port: 8081
  servlet:
    context-path: /user-service-api

keycloak:
  enabled: true
  auth-server-url: http://localhost:8484/auth
  realm: test
  resource: user-service
  credentials:
    secret: nQzqrpPArNPXaepx52PXibNBPerZ0Yee